# projects/rwby_vacuo_arc/dataset_config.toml

[general]
resolution = 1024
batch_size = 1

[[datasets]]

  # --- Batch 1 ---
  [[datasets.subsets]]
  image_dir = '/home/librad.laureateinstitute.org/mferguson/Visual-Novel-Writer/projects/rwby_vacuo_arc/training_data/20_blake'
  num_repeats=20

  [[datasets.subsets]]
  image_dir = '/home/librad.laureateinstitute.org/mferguson/Visual-Novel-Writer/projects/rwby_vacuo_arc/training_data/20_cinder'
  num_repeats=20

  [[datasets.subsets]]
  image_dir = '/home/librad.laureateinstitute.org/mferguson/Visual-Novel-Writer/projects/rwby_vacuo_arc/training_data/20_coco'
  num_repeats=20

  [[datasets.subsets]]
  image_dir = '/home/librad.laureateinstitute.org/mferguson/Visual-Novel-Writer/projects/rwby_vacuo_arc/training_data/20_elm'
  num_repeats=20

  # --- Batch 2 ---
  [[datasets.subsets]]
  image_dir = '/home/librad.laureateinstitute.org/mferguson/Visual-Novel-Writer/projects/rwby_vacuo_arc/training_data/20_emerald'
  num_repeats=20

  [[datasets.subsets]]
  image_dir = '/home/librad.laureateinstitute.org/mferguson/Visual-Novel-Writer/projects/rwby_vacuo_arc/training_data/20_ghira'
  num_repeats=20

  [[datasets.subsets]]
  image_dir = '/home/librad.laureateinstitute.org/mferguson/Visual-Novel-Writer/projects/rwby_vacuo_arc/training_data/20_glynda'
  num_repeats=20

  [[datasets.subsets]]
  image_dir = '/home/librad.laureateinstitute.org/mferguson/Visual-Novel-Writer/projects/rwby_vacuo_arc/training_data/20_harriet'
  num_repeats=20

  # --- Batch 3 ---
  [[datasets.subsets]]
  image_dir = '/home/librad.laureateinstitute.org/mferguson/Visual-Novel-Writer/projects/rwby_vacuo_arc/training_data/20_jaune'
  num_repeats=20

  [[datasets.subsets]]
  image_dir = '/home/librad.laureateinstitute.org/mferguson/Visual-Novel-Writer/projects/rwby_vacuo_arc/training_data/20_kali'
  num_repeats=20

  [[datasets.subsets]]
  image_dir = '/home/librad.laureateinstitute.org/mferguson/Visual-Novel-Writer/projects/rwby_vacuo_arc/training_data/20_maria'
  num_repeats=20

  [[datasets.subsets]]
  image_dir = '/home/librad.laureateinstitute.org/mferguson/Visual-Novel-Writer/projects/rwby_vacuo_arc/training_data/20_marrow'
  num_repeats=20

  # --- Batch 4 ---
  [[datasets.subsets]]
  image_dir = '/home/librad.laureateinstitute.org/mferguson/Visual-Novel-Writer/projects/rwby_vacuo_arc/training_data/20_mercury'
  num_repeats=20

  [[datasets.subsets]]
  image_dir = '/home/librad.laureateinstitute.org/mferguson/Visual-Novel-Writer/projects/rwby_vacuo_arc/training_data/20_neo'
  num_repeats=20

  [[datasets.subsets]]
  image_dir = '/home/librad.laureateinstitute.org/mferguson/Visual-Novel-Writer/projects/rwby_vacuo_arc/training_data/20_neptune'
  num_repeats=20

  [[datasets.subsets]]
  image_dir = '/home/librad.laureateinstitute.org/mferguson/Visual-Novel-Writer/projects/rwby_vacuo_arc/training_data/20_nora'
  num_repeats=20

  # --- Batch 5 ---
  [[datasets.subsets]]
  image_dir = '/home/librad.laureateinstitute.org/mferguson/Visual-Novel-Writer/projects/rwby_vacuo_arc/training_data/20_oobleck'
  num_repeats=20

  [[datasets.subsets]]
  image_dir = '/home/librad.laureateinstitute.org/mferguson/Visual-Novel-Writer/projects/rwby_vacuo_arc/training_data/20_oscar'
  num_repeats=20

  [[datasets.subsets]]
  image_dir = '/home/librad.laureateinstitute.org/mferguson/Visual-Novel-Writer/projects/rwby_vacuo_arc/training_data/20_peter'
  num_repeats=20

  [[datasets.subsets]]
  image_dir = '/home/librad.laureateinstitute.org/mferguson/Visual-Novel-Writer/projects/rwby_vacuo_arc/training_data/20_qrow'
  num_repeats=20

  # --- Batch 6 ---
  [[datasets.subsets]]
  image_dir = '/home/librad.laureateinstitute.org/mferguson/Visual-Novel-Writer/projects/rwby_vacuo_arc/training_data/20_raven'
  num_repeats=20

  [[datasets.subsets]]
  image_dir = '/home/librad.laureateinstitute.org/mferguson/Visual-Novel-Writer/projects/rwby_vacuo_arc/training_data/20_ren'
  num_repeats=20

  [[datasets.subsets]]
  image_dir = '/home/librad.laureateinstitute.org/mferguson/Visual-Novel-Writer/projects/rwby_vacuo_arc/training_data/20_robyn'
  num_repeats=20

  [[datasets.subsets]]
  image_dir = '/home/librad.laureateinstitute.org/mferguson/Visual-Novel-Writer/projects/rwby_vacuo_arc/training_data/20_ruby'
  num_repeats=20

  # --- Batch 7 ---
  [[datasets.subsets]]
  image_dir = '/home/librad.laureateinstitute.org/mferguson/Visual-Novel-Writer/projects/rwby_vacuo_arc/training_data/20_salem'
  num_repeats=20

  [[datasets.subsets]]
  image_dir = '/home/librad.laureateinstitute.org/mferguson/Visual-Novel-Writer/projects/rwby_vacuo_arc/training_data/20_sun'
  num_repeats=20

  [[datasets.subsets]]
  image_dir = '/home/librad.laureateinstitute.org/mferguson/Visual-Novel-Writer/projects/rwby_vacuo_arc/training_data/20_taiyang'
  num_repeats=20

  [[datasets.subsets]]
  image_dir = '/home/librad.laureateinstitute.org/mferguson/Visual-Novel-Writer/projects/rwby_vacuo_arc/training_data/20_tyrian'
  num_repeats=20

  # --- Batch 8 ---
  [[datasets.subsets]]
  image_dir = '/home/librad.laureateinstitute.org/mferguson/Visual-Novel-Writer/projects/rwby_vacuo_arc/training_data/20_velvet'
  num_repeats=20

  [[datasets.subsets]]
  image_dir = '/home/librad.laureateinstitute.org/mferguson/Visual-Novel-Writer/projects/rwby_vacuo_arc/training_data/20_weiss'
  num_repeats=20

  [[datasets.subsets]]
  image_dir = '/home/librad.laureateinstitute.org/mferguson/Visual-Novel-Writer/projects/rwby_vacuo_arc/training_data/20_winter'
  num_repeats=20

  [[datasets.subsets]]
  image_dir = '/home/librad.laureateinstitute.org/mferguson/Visual-Novel-Writer/projects/rwby_vacuo_arc/training_data/20_yang'
  num_repeats=20